---
export_recording:
  name: 导出录像
  description: 导出自定义录像或延时摄影。
  target:
    entity:
      integration: frigate
      domain: camera
      device_class: camera
  fields:
    playback_factor:
      name: 回放倍率
      description: 录像的回放倍率
      required: true
      advanced: false
      example: realtime
      default: realtime
      selector:
        select:
          options:
            - "realtime"
            - "timelapse_25x"
    start_time:
      name: 导出开始时间
      description: 录像导出的开始时间
      required: true
      advanced: false
      selector:
        datetime:
    end_time:
      name: 导出结束时间
      description: 录像导出的结束时间
      required: true
      advanced: false
      selector:
        datetime:

favorite_event:
  name: 收藏/取消收藏事件
  description: >
    将事件设为收藏或取消收藏。被收藏的事件将被无限期保留。
  target:
    entity:
      integration: frigate
      domain: camera
      device_class: camera
  fields:
    event_id:
      name: 事件 ID
      description: 需要收藏或取消收藏的事件 ID。
      required: true
      advanced: false
      example: "1656510950.19548-ihtjj7"
      default: ""
      selector:
        text:
    favorite:
      name: 是否收藏
      description: >
        选择是否将该事件标记为收藏。启用=收藏，禁用=取消收藏。
      required: false
      advanced: false
      example: true
      default: true
      selector:
        boolean:

ptz:
  name: 通过 PTZ 控制相机
  description: >
    平移/俯仰、变焦，或将相机移动到预设位。
  target:
    entity:
      integration: frigate
      domain: camera
      device_class: camera
  fields:
    action:
      name: PTZ 服务
      description: PTZ 动作类型
      required: true
      advanced: false
      example: move
      default: move
      selector:
        select:
          options:
            - "move"
            - "preset"
            - "stop"
            - "zoom"
    argument:
      name: PTZ 动作参数
      description: >
        移动：left/right/up/down；变焦：in/out；预设：预设名称
      required: false
      advanced: false
      example: down
      default: ""
      selector:
        text:

create_event:
  name: 创建事件
  description: >
    为指定相机创建一个带标签的手动事件。
  target:
    entity:
      integration: frigate
      domain: camera
      device_class: camera
  fields:
    label:
      name: 标签
      description: 事件的标签
      required: true
      advanced: false
      example: "Doorbell press"
      default: ""
      selector:
        text:
    sub_label:
      name: 子标签
      description: 事件的子标签
      required: false
      advanced: false
      example: "Front door"
      selector:
        text:
    duration:
      name: 持续时间
      description: >
        事件的预设时长。默认 30 秒，设置为 0 表示无限时长。
      required: false
      advanced: false
      example: 30
      default: 30
      selector:
        number:
          min: 0
          max: 300
          step: 1
    include_recording:
      name: 包含录像
      description: >
        是否在保存快照的同时保存对应录像。
      required: false
      advanced: false
      example: true
      default: true
      selector:
        boolean:

end_event:
  name: 结束事件
  description: >
    结束指定相机、给定 ID 的手动事件。
  target:
    entity:
      integration: frigate
      domain: camera
      device_class: camera
  fields:
    event_id:
      name: 事件 ID
      description: 要结束的事件 ID。
      required: true
      advanced: false
      example: "1656510950.19548-ihtjj7"
      default: ""
      selector:
        text:
